# Generated by Django 5.1.4 on 2024-12-30 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 30, 9, 39, 1, 542008, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
